[package]
name = "mika-rust-lodash"
version = "0.1.0"
edition = "2021"

[dependencies]
web-sys = "0.3.83"
js-sys = "0.3.68"
regex = "1.10.6"
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]